##########################################
# A pre-commit file is just a list of repos
# with options in yaml
##########################################
repos:

  ##########################################
  # Anton Babenko is the guy behing the Terraform AWS modules
  # this repo object pulls pre-commit hooks that he maintains
  # and select five hooks to run
  ##########################################
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.31.0
    hooks:
    # Add and sorts our docs
      - id: terraform_docs
        always_run: true
        args:
          - --args=--sort-by-required
      # apply terraform fmt
      - id: terraform_fmt
      # lint for best-practices
      - id: terraform_tflint
        alias: terraform_tflint_deep
        name: terraform_tflint_deep
        args:
          - --args=--deep
      - id: terraform_tflint
        alias: terraform_tflint_nocreds
        name: terraform_tflint_nocreds
      # terraform security check
      - id: terraform_tfsec

  ##########################################
  # local repo runs a hook called terraform_validate
  # and runs the bash inline
  ##########################################
  - repo: local
    hooks:
      - id: terraform_validate
        name: terraform_validate
        entry: |
          bash -c '
            AWS_DEFAULT_REGION=us-east-1
            declare -a DIRS
            for FILE in "$@"
            do
              DIRS+=($(dirname "$FILE"))
            done
            for DIR in $(printf "%s\n" "${DIRS[@]}" | sort -u)
            do
              cd $(dirname "$FILE")
              terraform init --backend=false
              terraform validate .
              cd ..
            done
          '
        language: system
        verbose: true
        files: \.tf(vars)?$
        exclude: examples

  ##########################################
  # hooks maintained by the pre-commit
  # out-of-the-box hooks check generic things
  # like proper json or yaml syntax and file attributes
  ##########################################
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.0.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: no-commit-to-branch
        args:
          - --branch
          - main
          - --branch
          - master
          - --branch
          - prod
      - id: pretty-format-json
        args:
          - --autofix
          - --top-keys=name,Name
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
        exclude: README.md
